### ISSUE TITLE
Evaluate if using "Performance Api" is better

### ISSUE THREAD

**Issue by meandmax** [atlassian/browser-interaction-time#3]
At the moment the library is using Date.now for timestamps. Does it make more sense to use the performance api instead?

https://developer.mozilla.org/en-US/docs/Web/API/Performance
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

**Comment by meandmax** [comment]
Makes sense, because sometimes dates are really not reliable and giving you weird times. Also `performance.now` gives you a timestamp relative to the page-load and not one based on date e.g. somewhere 1970s ^^

**Comment by hongphongnguyen** [comment]
Agree, `performance.now` relative to page load so it's exactly what we need.
