### ISSUE TITLE
How to get idleTime to reset when scrolling on a overflow scroll element?

### ISSUE THREAD

**Issue by bgold0** [atlassian/browser-interaction-time#66]
I'm using: `"browser-interaction-time": "^2.0.2"`

And I do the following:

    browserInteractionTime.startTimer();

    const cb = {
        multiplier: time => 1000,
        timeInMilliseconds: 1000,
        callback: () => console.log(browserInteractionTime.getTimeInMilliseconds())
    }

    browserInteractionTime.addTimeIntervalEllapsedCallback(cb)

However, when I leave my mouse still and I scroll on the page, the time in milliseconds stay's the same. Is there a way to accomplish this?

**Comment by meandmax** [comment]
@bgold0 Could you figure out which browser event we would should listen to? Then I can imagine also resetting idleTime when scrolling overflow.

**Comment by meandmax** [comment]
The events in the link are the events we currently listen to:
https://github.com/atlassian/browser-interaction-time/blob/master/src/browser-interaction-time.ts#L50-L58

**Comment by bgold0** [comment]
@meandmax I think you should check for scrolling on any child element as well. Like so:

    document.addEventListener('scroll', this.aFunction, true);

Notice the `, true)` at the end.

**Comment by meandmax** [comment]
I totally agree! That's a good feature and I will add that, I could think of 2 options API wise:
1. We allow passing an element or an array of elements where we will attach listeners to.
2. We use the option that you said above, I guess it is the `useCapture` option, correct?

What do you think?
